<?php

namespace AppBundle\Repository;

/**
 * GroupHasUserSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupHasUserSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
